services:
  - type: web
    name: dashboard-lenvie-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free

    envVars:
      - key: OMIE_APP_KEY
        sync: false

      - key: OMIE_APP_SECRET
        sync: false

      - key: REFRESH_TOKEN
        value: "Rafael.miranda@2026"

      - key: DB_PATH
        value: /data/dashboard.db

      - key: CORS_ORIGINS
        value: "*"